name: Scrape

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

permissions:
  contents: write

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pipenv'

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
        shell: bash

      - id: install-python-dependencies
        name: Install Python dependencies
        run: pipenv sync
        shell: bash

      - name: Scrape feeds
        run: pipenv run python -m src.scrape feeds
        shell: bash

      - name: Scrape adecks
        run: pipenv run python -m src.scrape adecks
        shell: bash

      - name: Convert GeoJSON
        run: pipenv run python -m src.convert geojson
        shell: bash

      - name: Datestamp
        run: date > data/timestamp.txt
        shell: bash

      - name: Commit results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git config pull.rebase false
          git status
          git pull origin $GITHUB_REF
          git add ./data
          git commit -m "Scrape" --author="palewire <palewire@users.noreply.github.com>" && git push || true
        shell: bash
